# Generated by Django 3.2.3 on 2021-05-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='visited_countries',
            field=models.ManyToManyField(to='info.Country'),
        ),
        migrations.AddField(
            model_name='person',
            name='country_of_origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='info.country'),
            preserve_default=False,
        ),
    ]
