# Generated by Django 3.2.3 on 2021-05-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gifs',
        ),
        migrations.AddField(
            model_name='gif',
            name='categories',
            field=models.ManyToManyField(to='main.Category'),
        ),
    ]
